"""empty message

Revision ID: 530ff2d5711d
Revises: 
Create Date: 2026-05-06 15:25:38.279765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530ff2d5711d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('promotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('button_text', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('variant_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name='fk_product_brand_id_brand'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)

    op.create_table('variant_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=80), nullable=False),
    sa.Column('meta', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['variant_type_id'], ['variant_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_type_id', 'value', name='uq_variant_option_type_value')
    )
    with op.batch_alter_table('variant_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variant_option_variant_type_id'), ['variant_type_id'], unique=False)

    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_option_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_type_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['variant_type_id'], ['variant_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'variant_type_id', name='uq_product_option_type')
    )
    with op.batch_alter_table('product_option_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_option_type_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_option_type_variant_type_id'), ['variant_type_id'], unique=False)

    op.create_table('product_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('stock', sa.Enum('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', name='stockstatus'), nullable=False),
    sa.Column('status', sa.String(length=5), nullable=False),
    sa.Column('option_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'option_key', name='uq_product_variant_option_key'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variant_option_key'), ['option_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variant_product_id'), ['product_id'], unique=False)

    op.create_table('product_variant_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variant_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variant_image_product_variant_id'), ['product_variant_id'], unique=False)

    op.create_table('product_variant_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('variant_option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['variant_option_id'], ['variant_option.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_variant_id', 'variant_option_id', name='uq_product_variant_option')
    )
    with op.batch_alter_table('product_variant_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variant_option_product_variant_id'), ['product_variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variant_option_variant_option_id'), ['variant_option_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variant_option_variant_option_id'))
        batch_op.drop_index(batch_op.f('ix_product_variant_option_product_variant_id'))

    op.drop_table('product_variant_option')
    with op.batch_alter_table('product_variant_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variant_image_product_variant_id'))

    op.drop_table('product_variant_image')
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variant_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_variant_option_key'))

    op.drop_table('product_variant')
    with op.batch_alter_table('product_option_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_option_type_variant_type_id'))
        batch_op.drop_index(batch_op.f('ix_product_option_type_product_id'))

    op.drop_table('product_option_type')
    op.drop_table('product_image')
    with op.batch_alter_table('variant_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variant_option_variant_type_id'))

    op.drop_table('variant_option')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_name'))
        batch_op.drop_index(batch_op.f('ix_product_category_id'))
        batch_op.drop_index(batch_op.f('ix_product_brand_id'))

    op.drop_table('product')
    op.drop_table('variant_type')
    op.drop_table('user')
    op.drop_table('promotion')
    op.drop_table('category')
    op.drop_table('brand')
    # ### end Alembic commands ###
